#!/bin/bash

if [[ -z $sf ]];then
	# echo $HOME/.ssh/id_rsa
	ssh -i $HOME/.ssh/id_rsa $1 $2
elif [[ $sf == id_rsa_* ]];then
	# echo $HOME/.ssh/$sf
	ssh -i $HOME/.ssh/$sf $1 $2
elif [[ $sf == id_dsa_* ]];then
	# echo $HOME/.ssh/$sf
	ssh -i $HOME/.ssh/$sf $1 $2
else
	# echo $HOME/.ssh/id_rsa_$sf
	ssh -i $HOME/.ssh/id_rsa_$sf $1 $2
fi
